version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:5.5.0
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  kafka-reactive-messaging-producer:
    image: kafka-showcase/kafka-reactive-messaging-producer:0
    environment:
      - KAFKA_HOST=kafka:9092
      - KAFKA_TOPIC=messages-topic
      - KAFKA_CLIENT_ID=kafka-reactive-messaging-producer
    ports:
      - 9082:9080
    depends_on:
      - kafka

  kafka-reactive-messaging-consumer:
    image: kafka-showcase/kafka-reactive-messaging-consumer:0
    environment:
      - KAFKA_HOST=kafka:9092
      - KAFKA_TOPIC=messages-topic
      - KAFKA_CLIENT_ID=kafka-reactive-messaging-consumer
      - KAFKA_GROUP_ID=kafka-reactive-messaging-consumer
    depends_on:
      - kafka
